package com.todoapp;

import java.util.List;
import java.util.UUID;
import javax.sql.DataSource;
import org.springframework.mock.web.MockHttpServletResponse;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.testcontainers.service.connection.ServiceConnection;
import org.springframework.core.env.Environment;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import static org.assertj.core.api.Assertions.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@Testcontainers
@SpringBootTest
@AutoConfigureMockMvc
@ActiveProfiles("test")
class TodoApplicationIT {

    @Container
    @ServiceConnection
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    @Autowired
    private DataSource dataSource;

    @Autowired
    private Environment environment;

    @Autowired
    private MockMvc mockMvc;

    @Test
    void contextLoads() {
    }

    @Test
    void flywaySchemaHistoryTableExists() {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        List<String> tables = jdbc.queryForList(
                "SELECT tablename FROM pg_catalog.pg_tables WHERE tablename = 'flyway_schema_history'",
                String.class);
        assertThat(tables).contains("flyway_schema_history");
    }

    @Test
    void postgresVersionIsCorrect() {
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        String version = jdbc.queryForObject("SHOW server_version", String.class);
        assertThat(version).startsWith("16.");
    }

    @Test
    void productionSafeConfigurationIsApplied() {
        assertThat(environment.getProperty("spring.jpa.hibernate.ddl-auto")).isEqualTo("validate");
        assertThat(environment.getProperty("spring.flyway.enabled")).isEqualTo("true");
        assertThat(environment.getProperty("spring.flyway.locations")).isEqualTo("classpath:db/migration");
    }

    @Test
    void healthEndpointReturnsSuccessEnvelope() throws Exception {
        mockMvc.perform(get("/api/v1/health"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.status").value("UP"))
            .andExpect(jsonPath("$.data.service").value("todo-app-backend"))
            .andExpect(jsonPath("$.data.timestamp").isNotEmpty());
    }

    @Test
    void readinessEndpointReportsDatabaseReady() throws Exception {
        mockMvc.perform(get("/api/v1/health/readiness"))
            .andExpect(status().isOk())
            .andExpect(jsonPath("$.success").value(true))
            .andExpect(jsonPath("$.data.status").value("READY"))
            .andExpect(jsonPath("$.data.database").value("UP"));
    }

    @Test
    void unknownEndpointReturnsErrorEnvelopeForAuthenticatedCallers() throws Exception {
        String token = authenticateAsProbe();

        mockMvc.perform(get("/api/v1/does-not-exist")
                        .header(HttpHeaders.AUTHORIZATION, "Bearer " + token))
            .andExpect(status().isNotFound())
            .andExpect(jsonPath("$.success").value(false))
            .andExpect(jsonPath("$.error.code").value("NOT_FOUND"))
            .andExpect(jsonPath("$.path").value("/api/v1/does-not-exist"))
            .andExpect(jsonPath("$.timestamp").isNotEmpty());
    }

    @Test
    void unknownEndpointIsRejectedForAnonymousCallers() throws Exception {
        mockMvc.perform(get("/api/v1/does-not-exist"))
            .andExpect(status().isUnauthorized())
            .andExpect(jsonPath("$.error.code").value("UNAUTHORIZED"));
    }

    @Test
    void correlationIdIsAutoGeneratedAndWellFormed() throws Exception {
        MvcResult result = mockMvc.perform(get("/api/v1/health"))
                .andExpect(status().isOk())
                .andReturn();
        String correlationId = result.getResponse().getHeader("X-Correlation-Id");
        assertThat(correlationId).isNotNull();
        assertThat(correlationId).matches(
                "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}");
    }

    @Test
    void correlationIdIsEchoedWhenProvided() throws Exception {
        MvcResult result = mockMvc.perform(get("/api/v1/health")
                        .header("X-Correlation-Id", "my-trace-123"))
                .andExpect(status().isOk())
                .andReturn();
        assertThat(result.getResponse().getHeader("X-Correlation-Id"))
                .isEqualTo("my-trace-123");
    }

    @Test
    void oversizedCorrelationIdIsReplacedWithGeneratedOne() throws Exception {
        String oversized = "a".repeat(65);
        MvcResult result = mockMvc.perform(get("/api/v1/health")
                        .header("X-Correlation-Id", oversized))
                .andExpect(status().isOk())
                .andReturn();
        String returned = result.getResponse().getHeader("X-Correlation-Id");
        assertThat(returned).isNotEqualTo(oversized);
        assertThat(returned).matches(
                "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}");
    }

    @Test
    void blankCorrelationIdIsReplacedWithGeneratedOne() throws Exception {
        MvcResult result = mockMvc.perform(get("/api/v1/health")
                        .header("X-Correlation-Id", "   "))
                .andExpect(status().isOk())
                .andReturn();
        String returned = result.getResponse().getHeader("X-Correlation-Id");
        assertThat(returned).isNotEqualTo("   ");
        assertThat(returned).matches(
                "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}");
    }

    private String authenticateAsProbe() throws Exception {
        mockMvc.perform(post("/api/v1/auth/register")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"username\":\"sysprobe\",\"email\":\"sysprobe@example.com\","
                        + "\"password\":\"S3cure-pass-42!\"}"))
            .andExpect(status().isCreated());

        MvcResult result = mockMvc.perform(post("/api/v1/auth/login")
                .contentType(MediaType.APPLICATION_JSON)
                .content("{\"username\":\"sysprobe\",\"password\":\"S3cure-pass-42!\"}"))
            .andExpect(status().isOk())
            .andReturn();

        com.fasterxml.jackson.databind.JsonNode data =
                new com.fasterxml.jackson.databind.ObjectMapper()
                        .readTree(result.getResponse().getContentAsString())
                        .path("data");
        return data.path("accessToken").asText();
    }
}