package com.todoapp.entity;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.Version;
import java.time.Instant;
import java.util.UUID;
import org.hibernate.annotations.UuidGenerator;
import org.hibernate.annotations.UuidGenerator.Style;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

/**
 * Common persistence foundation for every aggregate root in the domain.
 *
 * <ul>
 *   <li>{@code id} — application-generated UUID (random, record 4); generated by
 *       Hibernate {@link UuidGenerator}, stored in a PostgreSQL {@code uuid}
 *       primary-key column.</li>
 *   <li>{@code version} — optimistic-locking counter; incremented by Hibernate on
 *       every update so concurrent modifications are detected.</li>
 *   <li>{@code createdAt} / {@code updatedAt} — audited timestamps, maintained by
 *       Spring Data JPA auditing ({@link AuditingEntityListener}) as UTC
 *       {@link Instant} values.</li>
 * </ul>
 */
@MappedSuperclass
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    @Id
    @GeneratedValue
    @UuidGenerator(style = Style.RANDOM)
    @Column(name = "id", nullable = false, updatable = false)
    private UUID id;

    @Version
    @Column(name = "version", nullable = false)
    private long version;

    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    public UUID getId() {
        return id;
    }

    public long getVersion() {
        return version;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }
}