-- =============================================================================
-- V1: users — account/security data (no profile data).
-- =============================================================================
-- Design notes:
--   * id            : UUID primary key, generated by the application (Hibernate
--                     random UUID v4) on persist.
--   * username      : required, unique, max 50 chars. The application trims and
--                     lower-cases it before saving; the CHECK constraint below
--                     enforces the normalized (lowercase) form as a final
--                     database-level guarantee so duplicates are impossible.
--                     The UNIQUE constraint backs the username lookup index.
--   * email         : required, unique, max 255 chars, normalized the same way.
--   * password_hash : persistence-only Bcrypt-style string. NEVER exposed via
--                     API DTOs. Hashing/verification arrives with auth.
--   * account_status: extensible lifecycle enum, validated by CHECK.
--   * version       : optimistic-locking counter owned by Hibernate (@Version);
--                     starts at 0 on insert.
--   * created_at / updated_at : UTC timestamps, maintained by Spring Data JPA
--                     auditing. (Instant -> timestamp with time zone)
--   * last_login_at : nullable UTC instant.
-- =============================================================================

CREATE TABLE users (
    id             UUID         PRIMARY KEY,
    username       VARCHAR(50)  NOT NULL,
    email          VARCHAR(255) NOT NULL,
    password_hash  VARCHAR(255) NOT NULL,
    account_status VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    last_login_at  TIMESTAMPTZ,
    version        BIGINT       NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ  NOT NULL,
    updated_at     TIMESTAMPTZ  NOT NULL,

    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email    UNIQUE (email),

    CONSTRAINT ck_users_account_status
        CHECK (account_status IN ('ACTIVE', 'DISABLED', 'LOCKED')),
    CONSTRAINT ck_users_username_normalized CHECK (username = lower(username)),
    CONSTRAINT ck_users_email_normalized    CHECK (email    = lower(email)),
    CONSTRAINT ck_users_timestamps          CHECK (updated_at >= created_at)
);