-- =============================================================================
-- V4: refresh_tokens — opaque, revocable, rotated login sessions.
-- =============================================================================
-- Design notes:
--   * id            : UUID primary key, generated by the application.
--   * user_id       : owning account. FK ON DELETE CASCADE: deleting a user
--                     removes every of its sessions immediately.
--   * token_hash    : SHA-256 hex (64 chars) of the opaque refresh token. ONLY
--                     the hash is stored; the raw token is returned once to the
--                     client at issue time and cannot be recovered from storage.
--   * expires_at    : hard maximum lifetime (default 30 days). Rotation MUST NOT
--                     extend past this instant; the device must re-login.
--   * last_used_at  : peak refresh activity observability / rotation audit trail.
--   * revoked_at    : set on logout or rotation of a stale token; a revoked token
--                     is permanently dead (REFRESH_TOKEN_INVALID for the client).
--   * version / created_at / updated_at : same conventions as the other tables.
-- =============================================================================

CREATE TABLE refresh_tokens (
    id           UUID        PRIMARY KEY,
    user_id      UUID        NOT NULL,
    token_hash   VARCHAR(64) NOT NULL,
    expires_at   TIMESTAMPTZ NOT NULL,
    last_used_at TIMESTAMPTZ,
    revoked_at   TIMESTAMPTZ,
    version      BIGINT      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL,
    updated_at   TIMESTAMPTZ NOT NULL,

    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),

    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,

    CONSTRAINT ck_refresh_tokens_revoked_at_after_created
        CHECK (revoked_at IS NULL OR revoked_at >= created_at),
    CONSTRAINT ck_refresh_tokens_timestamps
        CHECK (updated_at >= created_at)
);

CREATE INDEX idx_refresh_tokens_user_id     ON refresh_tokens (user_id);
CREATE INDEX idx_refresh_tokens_expires_at  ON refresh_tokens (expires_at);

COMMENT ON TABLE refresh_tokens IS
    'Persisted login sessions; stores only the SHA-256 hash of each opaque '
    'refresh token and supports rotation, expiry and logout revocation.';